# Generated by Django 4.1.1 on 2022-09-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megastore', '0002_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
