# Generated by Django 4.0.5 on 2022-07-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='document',
            field=models.FileField(max_length=500, upload_to='pic/'),
        ),
    ]
